---
title: "Stat6242 Homework 3"
author: "Jonathan Hamburg"
date: "October 14, 2016"
output: 
  pdf_document: 
    keep_tex: yes
---

```{r setup}
library(np)
library(caret)
```


```{r qC}

bandwidthByCV <- function(x, y, h, nfold = 10) {
  # Load require packages
  require(caret)
  require(np)
  
  # If bandwiths aren't specified, add defaults
  if (missing(h)) {
    h <- seq(from = 0, to = 1, length.out = 100)
  }

  # Argument logic
  stopifnot(length(x) > 1, length(x) == length(y), nfold == trunc(nfold),
            nfold <= length(x), length(h) > 1)

  # Create an empty matrix to fill in
  foldMSEs <- matrix(NA, nrow = nfold, ncol = length(h))
  colnames(foldMSEs) <- h
  
  # Create folds for cv
  n <- length(x)
  flds <- caret::createFolds(x, k = nfold, list = TRUE, returnTrain =FALSE)

  # For each fold and bandwidth --- calculate MSE
  for (i in seq_along(flds)) {
    fold <- flds[[i]]
    trainX <- x[fold]
    trainY <- y[fold]
    testX <- x[-fold]
    testY <- y[-fold]
    for (n in seq_along(h)) {
      bw <- h[n]
      mod <- np::npreg(bws = bw, txdat = trainX, tydat = trainY,
                       exdat = testX, eydat = testY)
      foldMSEs[i, n] <- mod$MSE
    }
  }
  
  # Find average MSE for each bandwidth and the find the best one
  mseCV <- colMeans(foldMSEs)
  bestK <- mseCV[which.min(mseCV)]
  
  res <- list('bestBandwidth' = bestK,
              'cvMSEs' = mseCV,
              'foldMSEs' = foldMSEs)
  res
}
```


####################################
# For simulation

```{r qd data simulation}
set.seed(10)
X <- runif(1000, -4, 4)
eps <- rnorm(1000, mean = 0, sd = .01 ^ 2)
Y <- (exp(7 * X) / (1 + exp(7 * X))) + eps
```

Will calcuate based on K optimal. Since we do not know the first and second
derivatives for m(x), we will use the approximation of K = n ^ -1/5.

```{r qd kopt}
#######################
# Kopt ----
#######################

n <- length(X)
kopt <- n ^ (-1/5)

koptMod <- np::npreg(Y ~ X, bws = kopt)
koptMSE <- koptMod$MSE
```


```{r qd kplugin}
#######################
# K Plugin ----
#######################

n <- length(X)
kplug <- 1.06 * sd(X) * n ^ (-1/5)

kplugMod <- np::npreg(Y ~ X, bws = kplug)
kplugMSE <- kplugMod$MSE
```


```{r qd kcv}
#######################
# K CV ----
#######################

kcvMod <- bandwidthByCV(X, Y, nfold = 10)

kcvMSE <- kcvMod$bestBandwidth

cat(paste('Cross Validation MSE:', unname(kcvMSE), 
      '\nBandwidth:', names(kcvMSE)))
```


```{r summary kcv}
#######################
# Summary of Results ----
#######################

data.frame(method = c('Opt', 'Plugin', 'CV'), 
           bandwidth = c(kopt, kplug, as.numeric(names(kcvMSE))),
           mse = c(koptMSE, kplugMSE, unname(kcvMSE)))

```


